name: Deploy Application

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - staging

jobs:
  test-application:
    name: Test Application
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy-application:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test-application
    if: ${{ !contains(github.event.head_commit.message, '[skip deploy]') }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Deploy Application for Staging
        if: github.ref == 'refs/heads/staging'
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.ENVOYER_STAGING_DEPLOY_URL }}
          method: 'GET'

      - name: Deploy Application for Production
        if: github.ref == 'refs/heads/master'
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.ENVOYER_PRODUCTION_DEPLOY_URL }}
          method: 'GET'
