name: Deploy Application

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: (contains(github.ref, 'tags') && ! contains(github.ref, 'prerelease')) || github.ref == 'refs/heads/master'
    environment:
      name: production
      url: https://perscom.io
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Get Version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.FORGE_SSH_PRIVATE_KEY }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none
          tools: composer

      - name: Require Forge CLI
        run: composer global require laravel/forge-cli

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Javascript Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy Application
        run: |
          forge server:switch ${{ secrets.FORGE_SERVER_NAME }}
          forge deploy ${{ secrets.FORGE_PRODUCTION_SERVER_SITE }}
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}

      - name: Create Sentry Release
        uses: getsentry/action-release@v3
        with:
          environment: production
          release: ${{ env.VERSION }}
          sourcemaps: ./public/build/assets

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Invalidate Cloudfront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_PRODUCTION }}
          PATHS: "/*"

      - name: Purge Cloudflare Cache
        uses: nathanvaughn/actions-cloudflare-purge@v4.0.0
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
          cf_auth: ${{ secrets.CLOUDFLARE_API_KEY }}
          hosts: |
            perscom.io

      - name: Detect API Related Changes
        id: api-changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            api:
              - app/Models/**
              - app/Http/Controllers/Api/**
              - app/Http/Requests/Api/**
              - config/api.php

      - name: Purge Fastly Cache
        uses: yukukotani/fastly-purge-action@v1
        if: steps.api-changes.outputs.api == 'true'
        with:
          api-token: ${{ secrets.FASTLY_TOKEN_PRODUCTION }}
          service-id: ${{ secrets.FASTLY_SERVICE_PRODUCTION }}
          target: ${{ secrets.FASTLY_URL_PRODUCTION }}
          soft: true

  staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: contains(github.ref, 'prerelease') || github.ref == 'refs/heads/staging'
    environment:
      name: staging
      url: https://staging.perscom.io
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Get Version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.FORGE_SSH_PRIVATE_KEY }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none
          tools: composer

      - name: Require Forge CLI
        run: composer global require laravel/forge-cli

      - name: Deploy Application
        run: |
          forge server:switch ${{ secrets.FORGE_SERVER_NAME }}
          forge deploy ${{ secrets.FORGE_STAGING_SERVER_SITE }}
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Invalidate Cloudfront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_STAGING }}
          PATHS: "/*"

      - name: Purge Cloudflare Cache
        uses: nathanvaughn/actions-cloudflare-purge@v4.0.0
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
          cf_auth: ${{ secrets.CLOUDFLARE_API_KEY }}
          hosts: |
            staging.perscom.io

      - name: Detect API Related Changes
        id: api-changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            api:
              - app/Models/**
              - app/Http/Controllers/Api/**
              - app/Http/Requests/Api/**
              - config/api.php

      - name: Purge Fastly Cache
        uses: yukukotani/fastly-purge-action@v1
        if: steps.api-changes.outputs.api == 'true'
        with:
          api-token: ${{ secrets.FASTLY_TOKEN_STAGING }}
          service-id: ${{ secrets.FASTLY_SERVICE_STAGING }}
          target: single-url
          url: ${{ secrets.FASTLY_URL_STAGING }}
          soft: true
