name: Static Analysis and Linter

on:
  pull_request:

jobs:
  lint-application:
    name: Run Linter and Static Analysis
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip lint]') }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install NCC
        run: npm install -g @vercel/ncc

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Javascript Dependencies
        run: npm ci

      - name: Build Alpine.js Components
        run: |
          for dir in resources/js/components/*/; do
            echo "Building component in $dir"
            cd $dir || continue
            dirname=$(basename "$dir")
            ncc build index.js -o "../../dist/components/$dirname" -m
            cd - > /dev/null || continue
          done

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          ini-values: error_reporting=E_ALL
          tools: composer
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Configure Composer Authentication
        run: |
          composer config http-basic.spark.laravel.com ${{ secrets.SPARK_USERNAME }} ${{ secrets.SPARK_API_TOKEN }}
          composer config http-basic.whizzy.dev ${{ secrets.FILAMENT_USERNAME }} ${{ secrets.FILAMENT_PASSWORD }}

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Build Project
        run: |
          npm run build
          npm run build:landing

      - name: Run JS Linter
        run: |
          echo "Running Prettier $(prettier --version)"
          npm run format:test

      - name: Run PHP Linter
        run: |
          echo "Running $(./vendor/bin/pint --version)"
          composer test:lint

      - name: Run Static Analysis
        run: |
          echo "Running $(./vendor/bin/phpstan --version)"
          composer test:types
