name: PERSCOM CI/CD

on:
  push:
    branches:
      - master
      - prerelease

jobs:
  delpoy-application:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.FORGE_SSH_PRIVATE_KEY }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none
          tools: composer

      - name: Require Forge CLI
        run: composer global require laravel/forge-cli

      - name: Bump Application Version and Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          default_prerelease_bump: prerelease
          release_branches: master
          pre_release_branches: prerelease
          append_to_pre_release_tag: prerelease

      - name: Generate API Specification File
        run: php artisan perscom:specs --format=yaml

      - name: Generate Swagger API UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          version: ${{ steps.tag_version.outputs.new_tag }}
          spec-file: app/storage/specs/specs.yaml

      - name: Deploy API Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui

      - name: Deploy Application for Staging
        if: github.ref == 'refs/heads/prerelease'
        run: |
          forge server:switch ${{ secrets.FORGE_SERVER_NAME }}
          forge deploy ${{ secrets.FORGE_STAGING_SERVER_SITE }}
          forge command ${{ secrets.FORGE_STAGING_SERVER_SITE }} --command="php artisan env:set APP_VERSION ${{ steps.tag_version.outputs.new_tag }}"
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}

      - name: Deploy Application for Production
        if: github.ref == 'refs/heads/master'
        run: |
          forge server:switch ${{ secrets.FORGE_SERVER_NAME }}
          forge deploy ${{ secrets.FORGE_PRODUCTION_SERVER_SITE }}
          forge command ${{ secrets.FORGE_PRODUCTION_SERVER_SITE }} --command="php artisan env:set APP_VERSION ${{ steps.tag_version.outputs.new_tag }}"
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
