name: Test Suite

on:
  push:
    branches:
      - develop
      - master
      - staging
  pull_request:
  workflow_call:

jobs:
  test-application:
    name: Run PHPUnit Tests
    runs-on: ubuntu-22.04-16
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install NCC
        run: npm install -g @vercel/ncc

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Javascript Dependencies
        run: npm ci

      - name: Build Alpine.js Components
        run: |
          for dir in resources/js/components/*/; do
            echo "Building component in $dir"
            cd $dir || continue
            dirname=$(basename "$dir")
            ncc build index.js -o "../../dist/components/$dirname" -m
            cd - > /dev/null || continue
          done

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, :psr
          ini-values: error_reporting=E_ALL, xdebug.mode="develop,coverage"
          tools: composer
          coverage: xdebug
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Configure Composer Authentication
        run: |
          composer config http-basic.spark.laravel.com ${{ secrets.SPARK_USERNAME }} ${{ secrets.SPARK_API_TOKEN }}
          composer config http-basic.whizzy.dev ${{ secrets.FILAMENT_USERNAME }} ${{ secrets.FILAMENT_PASSWORD }}
          composer config http-basic.filament-filter-sets.composer.sh ${{ secrets.FILTER_SETS_USERNAME }} ${{ secrets.FILTER_SETS_PASSWORD }}

      - name: Composer Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Build Project
        run: npm run build

      - name: Install Passport Keys
        run: php artisan passport:keys --force

      - name: Make Environment File
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Clear Cache
        run: php artisan optimize:clear

      - name: Execute Tests
        run: php artisan test --parallel

      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./clover.xml
          verbose: true

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: storage/logs/
